default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 30
  host: <%= ENV.fetch('DATABASE_HOST') %>
  username: <%= ENV.fetch('DATABASE_USERNAME') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') %>
  port: <%= ENV.fetch('DATABASE_PORT') %>
  database: <%= ENV.fetch('DATABASE_DB') %>

development:
  <<: *default

production:
  <<: *default